apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sidekiq
    component: redis
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sidekiq
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
---