apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: sidekiq
    component: redis
spec:
  ports:
  - port: 6379
    name: redis-port
    targetPort: 6379
    protocol: TCP
  selector:
    app: sidekiq
    component: redis