apiVersion: v1
kind: Service
metadata:
  name: sidekiq
  labels:
    app: sidekiq
    component: sidekiq
spec:
  ports:
  - port: 80
    name: sidekiq-port
    targetPort: 80
    protocol: TCP
  selector:
    app: sidekiq
    component: sidekiq
---